[package]
name = "raytracing-in-a-weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl_ops = "0.1.1"
image = "0.23.14"
rand = "0.8.4"
rayon = "1.5.1"